### ISSUE TITLE
有个网站ZBG.COM，应该是用了此框架，报如下错误，求请教

### ISSUE THREAD

**Issue by wkshare** [helyho/Voovan#5]
这是因为请求的格式导致，还是服务端的逻辑问题？

那边官方不回复，所以这里先咨询下可能的原因

RequestMethod: POST <hr/>StatusCode: 500 <hr/>RequestPath: /exchange/fund/controller/website/fundcontroller/findbypage <hr/>ErrorMessage: java.lang.Exception: com.dd.http.server.exception.AnnotationRouterException: Process annotation router error. URL: /exchange/fund/controller<br/>java.lang.IllegalArgumentException: java.lang.ClassCastException@1df08df <hr/>Version: Voovan-WebServer/v3.2.0 <hr/>Description: <br> java.lang.Exception: com.dd.http.server.exception.AnnotationRouterException: Process annotation router error. URL: /exchange/fund/controlle<br> java.lang.IllegalArgumentException: java.lang.ClassCastException@1df08df<br> com.dd.http.server.HttpDispatcher.disposeRoute(HttpDispat<br> java.lang.Thread.run(Thread.java:748)<br> <br> com.dd.http.server.exception.AnnotationRouterException: Process annotation router error<br> java.lang.IllegalArgumentException: java.lang.ClassCastException@1df08df<br> com.dd.service.common.ServiceRouter.process(ServiceRouter<br> java.lang.Thread.run(Thread.java:748)<br> <br> java.lang.IllegalArgumentException: java.lang.ClassCastException@1df08df<br> sun.reflec<br> java.lang.Thread.run(Thread.java:748) <hr/>rker.run(ThreadPoolExecutor.java:624)a:43)

**Comment by helyho** [comment]
参数做类型转换时的异常
